name: flutter_country_selector
description: how a country picker to select a country
version: 1.0.3
repository: https://github.com/cedvdb/flutter_country_selector
homepage: https://github.com/cedvdb/flutter_country_selector

environment:
  sdk: ">=3.2.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ">=0.18.1 <=1.0.0"
  diacritic: ^0.1.5
  circle_flags: ^4.0.1
  # for iso codes, phone_numbers_parser needs to stay currently
  # as the flutter_country_selector library needs to be
  # compatible with phone_form_field
  phone_numbers_parser:
    git:
      url: https://github.com/fuadmostafij6/phone_numbers_parser.git
      ref: dev

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  generate: true
